name: SaveInventory
version: '${project.version}'
main: dev.DatxCute.SaveInventory
author: DatxCute
api-version: '1.20'

commands:
  save-inventory:
    permission: saveinventory.save
  save-inventory-load:
    permission: saveinventory.load
